### ISSUE TITLE
JSON-RPC deserialization exception during initialization

### ISSUE THREAD

**Issue by lauri-n** [jasonlyu123/SvelteVisualStudio#46]
I've recently started getting this error in VS2022 when loading up a project using Svelte:

![image](https://user-images.githubusercontent.com/42430379/166105990-cbd80611-5b73-4494-afa8-7da4267cbebf.png)

More info from the VS logs.

```
Newtonsoft.Json.JsonSerializationException: Deserializing JSON-RPC result to type InitializeResult failed with JsonSerializationException: Exception of type &apos;Newtonsoft.Json.JsonSerializationException&apos; was thrown.
   at StreamJsonRpc.JsonMessageFormatter.JsonRpcResult.GetResult[T]()
   at StreamJsonRpc.JsonRpc.&lt;InvokeCoreAsync&gt;d__143`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.JsonRpcExtensionMethods.&lt;SendMethodRequestAsync&gt;d__1`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.&lt;SendInitializeRequestAsync&gt;d__101.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.&lt;InitializeAsync&gt;d__100.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.&lt;InitializeAsync&gt;d__100.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.ThreadingTools.&lt;WithCancellationSlow&gt;d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.&lt;ActivateLanguageClientAsync&gt;d__107.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

```

My VS version:

Version 17.1.6
VisualStudio.17.Release/17.1.6+32421.90

The Svelte For Visual Studio extension is updated to the latest 1.9.0 version.

**Comment by jasonlyu123** [comment]
Thanks for the report. It is a new feature in the svelte language server that is incompatible. I release 1.19.2 with a downgraded deps version. And would see what can I to fix this in the upstream.

**Comment by lauri-n** [comment]
Working nicely again with 1.9.2, thanks!
